### ISSUE TITLE
Show data immutability e.g. this data was signed by this agent at this timestamp; track any changes to the data post timestamp

### ISSUE THREAD

**Issue by dcatki** [holochain-open-dev/holoom#21]

**Comment by 8e8b2c** [comment]
> Currently no documents have timestamps, this needs changing in the happ. This probably makes the most sense on OracleDocument. One possible drawback is that two near-simultaneous asserts of the same data would have different entry hashes. (Is it worth nesting entries to address this? An idea possibly worth revisiting when considering https://github.com/holochain-open-dev/holoom/issues/15))

Scrap that, I'd completely overlooked that Records have timestamps
